FROM node:18-alpine AS builder

ARG AUTHORIZED_EMAILS
ENV AUTHORIZED_EMAILS $AUTHORIZED_EMAILS

ARG GOOGLE_CLIENT_ID
ENV GOOGLE_CLIENT_ID $GOOGLE_CLIENT_ID

ARG GOOGLE_CLIENT_SECRET
ENV GOOGLE_CLIENT_SECRET $GOOGLE_CLIENT_SECRET

ARG ORIGIN
ENV ORIGIN $ORIGIN

ARG NEXTAUTH_URL
ENV NEXTAUTH_URL $NEXTAUTH_URL

ARG NEXTAUTH_URL
ENV NEXTAUTH_URL $NEXTAUTH_URL

ARG NEXTAUTH_URL_INTERNAL
ENV NEXTAUTH_URL_INTERNAL $NEXTAUTH_URL_INTERNAL

WORKDIR /app
COPY package*.json .
RUN npm ci
COPY . .
RUN npx prisma generate
RUN npm run build
RUN npm prune --production
RUN echo ${NEXTAUTH_URL}

FROM node:18-alpine
WORKDIR /app
COPY --from=builder /app/build build/
COPY --from=builder /app/node_modules node_modules/
COPY package.json .
EXPOSE 3000
ENV NODE_ENV=production
CMD [ "node", "build" ]